package power_configuration

import "github.com/shimmeringbee/zcl"

const (
	MainsVoltage   = zcl.AttributeID(0x0000)
	MainsFrequency = zcl.AttributeID(0x0001)

	MainsAlarmMask             = zcl.AttributeID(0x0010)
	MainsVoltageMinThreshold   = zcl.AttributeID(0x0011)
	MainsVoltageMaxThreshold   = zcl.AttributeID(0x0012)
	MainsVoltageDwellTripPoint = zcl.AttributeID(0x0013)

	BatteryVoltage             = zcl.AttributeID(0x0020)
	BatteryPercentageRemaining = zcl.AttributeID(0x0021)

	BatteryManufacturer           = zcl.AttributeID(0x0030)
	BatterySize                   = zcl.AttributeID(0x0031)
	BatteryAHrRating              = zcl.AttributeID(0x0032)
	BatteryQuantity               = zcl.AttributeID(0x0033)
	BatteryRatedVoltage           = zcl.AttributeID(0x0034)
	BatteryAlarmMask              = zcl.AttributeID(0x0035)
	BatteryVoltageMinThreshold    = zcl.AttributeID(0x0036)
	BatteryVoltageThreshold1      = zcl.AttributeID(0x0037)
	BatteryVoltageThreshold2      = zcl.AttributeID(0x0038)
	BatteryVoltageThreshold3      = zcl.AttributeID(0x0039)
	BatteryPercentageMinThreshold = zcl.AttributeID(0x003a)
	BatteryPercentageThreshold1   = zcl.AttributeID(0x003b)
	BatteryPercentageThreshold2   = zcl.AttributeID(0x003c)
	BatteryPercentageThreshold3   = zcl.AttributeID(0x003d)
	BatteryAlarmState             = zcl.AttributeID(0x003e)

	BatterySource2Voltage             = zcl.AttributeID(0x0040)
	BatterySource2PercentageRemaining = zcl.AttributeID(0x0041)

	BatterySource2Manufacturer           = zcl.AttributeID(0x0050)
	BatterySource2Size                   = zcl.AttributeID(0x0051)
	BatterySource2AHrRating              = zcl.AttributeID(0x0052)
	BatterySource2Quantity               = zcl.AttributeID(0x0053)
	BatterySource2RatedVoltage           = zcl.AttributeID(0x0054)
	BatterySource2AlarmMask              = zcl.AttributeID(0x0055)
	BatterySource2VoltageMinThreshold    = zcl.AttributeID(0x0056)
	BatterySource2VoltageThreshold1      = zcl.AttributeID(0x0057)
	BatterySource2VoltageThreshold2      = zcl.AttributeID(0x0058)
	BatterySource2VoltageThreshold3      = zcl.AttributeID(0x0059)
	BatterySource2PercentageMinThreshold = zcl.AttributeID(0x005a)
	BatterySource2PercentageThreshold1   = zcl.AttributeID(0x005b)
	BatterySource2PercentageThreshold2   = zcl.AttributeID(0x005c)
	BatterySource2PercentageThreshold3   = zcl.AttributeID(0x005d)
	BatterySource2AlarmState             = zcl.AttributeID(0x005e)

	BatterySource3Voltage             = zcl.AttributeID(0x0060)
	BatterySource3PercentageRemaining = zcl.AttributeID(0x0061)

	BatterySource3Manufacturer           = zcl.AttributeID(0x0070)
	BatterySource3Size                   = zcl.AttributeID(0x0071)
	BatterySource3AHrRating              = zcl.AttributeID(0x0072)
	BatterySource3Quantity               = zcl.AttributeID(0x0073)
	BatterySource3RatedVoltage           = zcl.AttributeID(0x0074)
	BatterySource3AlarmMask              = zcl.AttributeID(0x0075)
	BatterySource3VoltageMinThreshold    = zcl.AttributeID(0x0076)
	BatterySource3VoltageThreshold1      = zcl.AttributeID(0x0077)
	BatterySource3VoltageThreshold2      = zcl.AttributeID(0x0078)
	BatterySource3VoltageThreshold3      = zcl.AttributeID(0x0079)
	BatterySource3PercentageMinThreshold = zcl.AttributeID(0x007a)
	BatterySource3PercentageThreshold1   = zcl.AttributeID(0x007b)
	BatterySource3PercentageThreshold2   = zcl.AttributeID(0x007c)
	BatterySource3PercentageThreshold3   = zcl.AttributeID(0x007d)
	BatterySource3AlarmState             = zcl.AttributeID(0x007e)
)
